#!/usr/bin/env node

// Webflow CMS → Gallery Config Sync
// Usage: node sync.js <gallery-id>
// Example: node sync.js beltline-app
//
// Requires .env file with:
//   WEBFLOW_API_TOKEN=your_token_here
//   WEBFLOW_COLLECTION_ID=your_collection_id
//
// Webflow CMS Collection should have fields:
//   - name (text)        → image title/ID
//   - image (image)      → the photo
//   - gallery (text)     → gallery name (e.g., "beltline-app")
//   - sort-order (number)→ display order
//   - size (text/select) → "1", "2", "3", "2x2", "tall"

const fs = require("fs");
const path = require("path");

// Load .env
const envPath = path.join(__dirname, ".env");
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, "utf-8");
  envContent.split("\n").forEach((line) => {
    const [key, ...vals] = line.split("=");
    if (key && vals.length) {
      process.env[key.trim()] = vals.join("=").trim();
    }
  });
}

const API_TOKEN = process.env.WEBFLOW_API_TOKEN;
const COLLECTION_ID = process.env.WEBFLOW_COLLECTION_ID;
const galleryId = process.argv[2];

if (!galleryId) {
  console.error("Usage: node sync.js <gallery-id>");
  console.error("Example: node sync.js beltline-app");
  process.exit(1);
}

if (!API_TOKEN || !COLLECTION_ID) {
  console.error("Missing WEBFLOW_API_TOKEN or WEBFLOW_COLLECTION_ID in .env");
  process.exit(1);
}

async function fetchAllItems() {
  const items = [];
  let offset = 0;
  const limit = 100;

  while (true) {
    const url = `https://api.webflow.com/v2/collections/${COLLECTION_ID}/items?limit=${limit}&offset=${offset}`;
    const res = await fetch(url, {
      headers: {
        Authorization: `Bearer ${API_TOKEN}`,
        "accept-version": "2.0.0",
      },
    });

    if (!res.ok) {
      const body = await res.text();
      console.error(`API error ${res.status}: ${body}`);
      process.exit(1);
    }

    const data = await res.json();
    items.push(...data.items);

    if (items.length >= data.pagination.total) break;
    offset += limit;
  }

  return items;
}

function parseSize(sizeStr) {
  if (!sizeStr) return 1;
  const s = String(sizeStr).toLowerCase().trim();
  if (s === "2" || s === "2w") return 2;
  if (s === "3" || s === "3w") return 3;
  if (s === "2x2") return "2x2";
  if (s === "tall") return "tall";
  return 1;
}

async function main() {
  console.log(`Fetching items from Webflow collection ${COLLECTION_ID}...`);
  const allItems = await fetchAllItems();

  // Filter by gallery field
  const galleryItems = allItems.filter((item) => {
    const fields = item.fieldData;
    return fields && fields.gallery === galleryId;
  });

  if (!galleryItems.length) {
    console.error(`No items found with gallery="${galleryId}"`);
    console.error(`Available gallery values: ${[...new Set(allItems.map((i) => i.fieldData?.gallery).filter(Boolean))].join(", ") || "none"}`);
    process.exit(1);
  }

  // Sort by sort-order field
  galleryItems.sort((a, b) => {
    const orderA = a.fieldData["sort-order"] || 0;
    const orderB = b.fieldData["sort-order"] || 0;
    return orderA - orderB;
  });

  // Build config
  const images = galleryItems.map((item) => {
    const fields = item.fieldData;
    const imageField = fields.image;
    const src = imageField?.url || imageField?.fileId || "";
    const name = fields.name || fields.slug || item.id;

    return {
      id: name.replace(/[^a-zA-Z0-9_-]/g, "_"),
      src: src,
      alt: fields.name || "Gallery Image",
      size: parseSize(fields.size),
    };
  });

  // Find title from first item or use gallery ID
  const title = galleryItems[0]?.fieldData?.["gallery-title"] || galleryId.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

  const config = {
    id: galleryId,
    title: title,
    subtitle: new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }),
    images: images,
  };

  const output = `// Gallery Config — ${config.title}
// Auto-generated by sync.js from Webflow CMS on ${new Date().toISOString().split("T")[0]}
// To regenerate: node sync.js ${galleryId}

window.GALLERY_CONFIG = ${JSON.stringify(config, null, 2)};
`;

  const outPath = path.join(__dirname, "galleries", `${galleryId}.js`);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output, "utf-8");

  console.log(`Wrote ${images.length} images to ${outPath}`);
  console.log("Done! Commit and push to update the live gallery.");
}

main().catch((err) => {
  console.error("Sync failed:", err.message);
  process.exit(1);
});
